% Script generated by Brainstorm (07-Nov-2021)

% Input files
sFiles = {...
    'D0179_chirp-ST/@rawD0179_chirp-ST_postcomp/data_0raw_D0179_chirp-ST_postcomp.mat', ...
    'D0320_chirp-ST/@rawD0320_chirp-ST_postcomp/data_0raw_D0320_chirp-ST_postcomp.mat', ...
    'D0339_chirp-ST/@rawD0339_chirp-ST_postcomp/data_0raw_D0339_chirp-ST_postcomp.mat'};
SubjectNames = {...
    'D0179_chirp-ST','D0320_chirp-ST', 'D0339_chirp-ST'};

% Start a new report
bst_report('Start', sFiles);



% Save and display report
ReportFile = bst_report('Save', sFiles);
bst_report('Open', ReportFile);
% bst_report('Export', ReportFile, ExportDir);


